name: Build rtkrcv

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        imageName: rinex20/rtklib
        platform: linux/amd64,linux/arm64,linux/arm/v7 # 你准备构建的镜像平台
        tag: latest-m # 默认latest，可以针对平台，修改tag
        dockerUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid
        dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
